// <auto-generated />
namespace DraftCraft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SlikeProizvoda_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SlikeProizvoda_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201804101102152_SlikeProizvoda_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
